services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: lvm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
volumes:
  pgdata: