services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: lvm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata: