// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fertilizer.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTmp = `-- name: CreateTmp :one
INSERT INTO Fertilizers (fertilizer_id, name)
VALUES ($1, $2)
RETURNING fertilizer_id, name
`

type CreateTmpParams struct {
	FertilizerID pgtype.UUID
	Name         pgtype.Text
}

func (q *Queries) CreateTmp(ctx context.Context, arg CreateTmpParams) (Fertilizer, error) {
	row := q.db.QueryRow(ctx, createTmp, arg.FertilizerID, arg.Name)
	var i Fertilizer
	err := row.Scan(&i.FertilizerID, &i.Name)
	return i, err
}
