// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Crop struct {
	CropID        pgtype.UUID
	SeedID        pgtype.UUID
	SoakingStart  pgtype.Timestamp
	SoakingEnd    pgtype.Timestamp
	StackingStart pgtype.Timestamp
	StackingEnd   pgtype.Timestamp
	LightsStart   pgtype.Timestamp
	LightsEnd     pgtype.Timestamp
}

type Fertilizer struct {
	FertilizerID pgtype.UUID
	Name         pgtype.Text
}

type Material struct {
	MaterialID     pgtype.UUID
	Name           pgtype.Text
	MaterialTypeID pgtype.UUID
	Main           pgtype.Bool
}

type MaterialType struct {
	MaterialTypeID pgtype.UUID
	Name           pgtype.Text
}

type Order struct {
	OrderID  pgtype.UUID
	Total    pgtype.Float8
	Shipping pgtype.Float8
}

type OrderItem struct {
	OrderItemID pgtype.UUID
	OrderID     pgtype.UUID
	OrderTypeID pgtype.UUID
	Name        pgtype.Text
	SeedID      pgtype.UUID
	MaterialID  pgtype.UUID
	SupplierID  pgtype.UUID
	Price       pgtype.Float8
}

type OrderType struct {
	OrderTypeID pgtype.UUID
	Name        pgtype.Text
}

type Seed struct {
	SeedID pgtype.UUID
	Name   pgtype.Text
	Type   pgtype.Text
}

type SeedInstruction struct {
	SeedInstructionID pgtype.UUID
	SeedID            pgtype.UUID
	SeedGrams         pgtype.Int4
	SoakingHours      pgtype.Int4
	StackingHours     pgtype.Int4
	BlackoutHours     pgtype.Int4
	LightsHours       pgtype.Int4
	YieldGrams        pgtype.Int4
	SpecialTreatment  pgtype.Text
}

type Supplier struct {
	SupplierID pgtype.UUID
	Name       pgtype.Text
	Url        pgtype.Text
	Suiss      pgtype.Bool
}

type Watering struct {
	WateringID   pgtype.UUID
	CropID       pgtype.UUID
	QuantityMl   pgtype.Int4
	FertilizerMl pgtype.Int4
	FertilizerID pgtype.UUID
}
